[package]
name = "speakeasy-core"
version = "1.1.0"
edition = "2024"
authors = ["Nathan Marley <nathan@glowberrylabs.com>"]
license = "MIT OR Apache-2.0"

[lib]
name = "speakeasy_core"
crate-type = ["staticlib", "lib"]

[dependencies]
hound = "3.5"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(target_os = "macos")'.dependencies]
whisper-rs = { version = "0.16", features = ["metal"] }

[target.'cfg(not(target_os = "macos"))'.dependencies]
whisper-rs = { version = "0.16" }

[profile.release]
lto = true
codegen-units = 1
